#!/bin/bash
#
# Prints out the artist and song that is playing in Cmus using the cmus-remote
# program. 
#
# Used with yabar.
#
# Author: clyde80
# Website: https://github.com/clyde80
# Fork: prazuvalov
# Website: https://github.com/prazuvalov
#
status=$(ps cax | grep cmus)
if [ -z "$status" ]; then
    echo ""
else
	artist=$(cmus-remote -Q | grep "tag artist")
    title=$(cmus-remote -Q | grep "tag title")
    if [ -z "$title"  ]; then
	    echo "  Unknown"
    else
    title=${title//"tag title "/""}
    artist=${artist//"tag artist "/""}
    echo "  $artist - $title"
    fi
fi
