#!/bin/bash
#
# Prints the connected wifi network using NetworkManager CLI (nmcli)
#
# Author: clyde80
# Website: https://github.com/clyde80
# Fork: prazuvalov
# Website: https://github.com/prazuvalov
#
# Replace enp3s0 with your own lan profile
#
lan=$(nmcli dev show enp3s0 | grep connected)
output=$(nmcli -t -f active,ssid dev wifi | grep "yes")
if [ ! -z "$output" ] && [ -z "$lan" ]; then
    output=${output//"yes:"/""}
    echo " $output"
else
	if [ ! -z "$lan" ]; then
		ip=$(ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p' | head -1)
		echo " $ip"
    else 
    	echo "Not Connected"
	fi
fi